# BEND/docker-compose.lite.yml
# A lightweight configuration that runs only the essential BEND services
# for powering an autonomous agent like AEGIS.
# Use with the --lite flag and a profile name, e.g., `manage.sh up --lite vllm`

version: "3.9"

networks:
  bend-net:
    driver: bridge

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "${QDRANT_PORT:-12006}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - bend-net

  retriever:
    build:
      context: ./rag
    container_name: retriever
    restart: unless-stopped
    ports:
      - "${RETRIEVER_PORT:-12007}:8000"
    depends_on:
      - qdrant
    volumes:
      - ./rag/docs:/app/docs
    environment:
      - BEND_API_KEY=${BEND_API_KEY}
      - OTEL_SERVICE_NAME=retriever
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - bend-net

  koboldcpp:
    profiles: ["koboldcpp"]
    build:
      context: .
      dockerfile: Dockerfile.build-services
      target: kobold-builder
      args:
        - GPU_ENABLED=${KOBOLD_GPU_ENABLED:-false}
    container_name: koboldcpp
    restart: unless-stopped
    ports:
      - "${KOBOLD_PORT:-12009}:5001"
    volumes:
      - ./models:/models
    command: >
      python3 koboldcpp.py
      --model /models/${KOBOLDCPP_MODEL_NAME}
      --host 0.0.0.0
      --port 5001
      --threads ${KOBOLD_THREADS:-16}
      --contextsize ${MODEL_CONTEXT_SIZE}
      --gpulayers ${KOBOLD_GPU_LAYERS:-0}
      --smartcontext
      --usemlock
    networks:
      - bend-net

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-12010}:6379"
    networks:
      - bend-net

  vllm:
    profiles: ["vllm"]
    image: openeuler/vllm-cpu:latest
    container_name: vllm
    restart: unless-stopped
    ports:
      - "${VLLM_PORT:-12011}:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ./models:/root/.cache/huggingface/hub
    command: >
      --model ${MODEL_NAME}
      --served-model-name aegis-agent-model
      --gpu-memory-utilization ${VLLM_GPU_MEMORY_UTILIZATION:-0.90}
    networks:
      - bend-net

volumes:
  qdrant_data: