version: "3.9"

networks:
  bend-net:
    driver: bridge

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "${OPENWEBUI_PORT:-12002}:3000"
    environment:
      - OLLM_API_BASE_URL=${OLLM_API_BASE_URL}
      - WEBUI_URL=http://localhost:12002
      - PORT=3000
      - ENABLE_PERSISTENT_CONFIG=false
    volumes:
      - openwebui_data:/app/backend/data
    networks:
      - bend-net

  whisper:
    build:
      context: .
      dockerfile: Dockerfile.build-services
      target: whisper-builder
      args:
        - GPU_ENABLED=${WHISPER_GPU_ENABLED:-false}
    container_name: whisper
    restart: unless-stopped
    ports:
      - "${WHISPER_PORT:-12003}:9000"
    networks:
      - bend-net

  piper:
    build:
      context: .
      dockerfile: Dockerfile.piper
    container_name: piper
    restart: unless-stopped
    environment:
      - LD_LIBRARY_PATH=./piper
    command: >
      python3 -m piper.http_server
      --model /data/${PIPER_VOICE:-en_US-lessac-medium}.onnx
      --port 59125
      --host 0.0.0.0
    ports:
      - "${PIPER_PORT:-12004}:59125"
    networks:
      - bend-net

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    ports:
      - "${GLANCES_PORT:-12005}:61208"
    pid: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GLANCES_OPT=-w
    networks:
      - bend-net

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "${QDRANT_PORT:-12006}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - bend-net

  retriever:
    build:
      context: ./rag
    container_name: retriever
    restart: unless-stopped
    ports:
      - "${RETRIEVER_PORT:-12007}:8000"
    depends_on:
      - qdrant
    volumes:
      - ./rag/docs:/app/docs
    environment:
      - BEND_API_KEY=${BEND_API_KEY}
      - OTEL_SERVICE_NAME=retriever
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - bend-net

  voiceproxy:
    build: ./voice-proxy
    container_name: voiceproxy
    restart: unless-stopped
    ports:
      - "${VOICEPROXY_PORT:-12008}:8001"
    depends_on:
      - whisper
      - piper
    environment:
      - BEND_API_KEY=${BEND_API_KEY}
      - OTEL_SERVICE_NAME=voiceproxy
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - bend-net

volumes:
  qdrant_data:
  openwebui_data: