# BEND/docker-compose.lite.yml
# A lightweight configuration that runs only the essential BEND services
# for powering an autonomous agent like AEGIS.
# Use with the --lite flag, e.g., `manage.sh up --lite`

networks:
  bend-net:
    driver: bridge

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "${QDRANT_PORT:-12006}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - bend-net

  retriever:
    build:
      context: ./rag
    container_name: retriever
    restart: unless-stopped
    ports:
      - "${RETRIEVER_PORT:-12007}:8000"
    depends_on:
      - qdrant
    volumes:
      - ./rag/docs:/app/docs
    environment:
      - OTEL_SERVICE_NAME=retriever
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - bend-net


  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-12009}:11434"
    volumes:
      - ./scripts/entrypoint-ollama.sh:/entrypoint-ollama.sh
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_PULL_MODEL=${OLLAMA_PULL_MODEL}
    entrypoint: /entrypoint-ollama.sh
    networks:
      - bend-net

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-12010}:6379"
    networks:
      - bend-net

  nemoguardrails:
    build:
      context: .
      dockerfile: Dockerfile.nemo
    container_name: nemoguardrails
    restart: unless-stopped
    command: ["nemoguardrails", "server", "--config=./config.co", "--default-config-id", "config"]
    ports:
      - "${GUARDRAILS_PORT:-12012}:8000"
    networks:
      - bend-net

volumes:
  qdrant_data:
  ollama_data: